name: codspeed-benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "master"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
      - name: Python-dev
        run: |
          apt-get update
          apt-get install -yq python3.11-dev

      - uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-codspeed
        run: cargo binstall cargo-codspeed -y

      - name: Build the benchmark target(s)
        run: |
          cargo codspeed build -p arrow --features test_utils,csv,json,chrono-tz,pyarrow,prettyprint
          cargo codspeed build -p parquet --features arrow,test_common,experimental,default
          cargo codspeed build -p arrow-array -p arrow-buffer -p arrow-cast -p arrow-json

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: cargo codspeed run
