name: codspeed-benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "master"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: |
          cargo codspeed build -p arrow --features test_utils,csv,json,chrono-tz,pyarrow,prettyprint # ✅, skipped arrow.comparison_kernel.eq scalar StringViewArray because it was failing on my macOs machine
          cargo codspeed build -p parquet --features arrow,test_common,experimental,default # ✅, skipped parquet.metadata bench because it requires a file that does not exists in repo
          cargo codspeed build -p arrow-array -p arrow-buffer -p arrow-cast -p arrow-json # ✅

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: cargo codspeed run
